[package]
name = "backit-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
bpaf = { version = "0.9.14", features = ["bright-color", "autocomplete"] }
backit-core = { path = "../backit-core" }
eyre = "0.6.12"
tokio = { version = "1.40.0", features = ["full"] }
